// Starter item catalog. Add more items by appending to `items` below.
//
// Each entry must include `width`/`height` for inventory placement, and
// should set `quality` (defaults to 'common'). `prefix`/`suffix` are
// optional and combined into the displayed name (e.g. "Sharp Short
// Dagger of the Bear"). `durabilityMax`/`conditioningMax` enable the
// green / yellow bars in the tooltip.

export const ITEM_PREFIXES = [
  'Sharp', 'Sturdy', 'Reinforced', 'Cursed', 'Hardened', 'Polished',
  'Vile', 'Ancient', 'Brutal', 'Soldier’s', 'Mighty', 'Savage',
];

export const ITEM_SUFFIXES = [
  'of the Bear', 'of the Wolf', 'of the Eagle', 'of Power',
  'of Vigor', 'of Endurance', 'of the Magus', 'of Cunning',
];

export const TOP_PREFIXES = ['Heroic', 'Legendary', 'Mythic'];
export const TOP_SUFFIXES = ['of Champions', 'of the Gods', 'of Eternity'];

export const items = {
  // ---------------- Weapons (mainHand) ----------------
  short_dagger: {
    itemId: 'short_dagger',
    name: 'Short Dagger',
    image: 'short-dagger',
    type: 'mainHand',
    quality: 'common',
    level: 1,
    damage: [1, 8],
    power: 4,
    probability: 20,
    sellPrice: 30,
    durability: 5680, durabilityMax: 5680,
    conditioning: 1418, conditioningMax: 1418,
    width: 1, height: 2,
  },
  short_sword: {
    itemId: 'short_sword',
    name: 'Short Sword',
    image: 'short-sword',
    type: 'mainHand',
    quality: 'common',
    level: 1,
    damage: [3, 5],
    power: 3,
    probability: 10,
    sellPrice: 50,
    durability: 6000, durabilityMax: 6000,
    conditioning: 1500, conditioningMax: 1500,
    width: 1, height: 3,
  },
  sharp_short_sword: {
    itemId: 'sharp_short_sword',
    name: 'Short Sword',
    prefix: 'Sharp',
    image: 'short-sword',
    type: 'mainHand',
    quality: 'green',
    level: 2,
    damage: [4, 7],
    strength: 1,
    power: 5,
    probability: 8,
    sellPrice: 90,
    durability: 6500, durabilityMax: 6500,
    conditioning: 1600, conditioningMax: 1600,
    width: 1, height: 3,
  },
  runic_sword: {
    itemId: 'runic_sword',
    name: 'Runic Sword',
    suffix: 'of the Magus',
    image: 'runic-sword',
    type: 'mainHand',
    quality: 'blue',
    level: 3,
    damage: [5, 9],
    intelligence: 2,
    power: 7,
    probability: 5,
    sellPrice: 210,
    durability: 7200, durabilityMax: 7200,
    conditioning: 1800, conditioningMax: 1800,
    width: 1, height: 3,
  },
  legendary_battle_axe: {
    itemId: 'legendary_battle_axe',
    name: 'Battle Axe',
    prefix: 'Legendary',
    suffix: 'of Champions',
    image: 'short-sword',
    type: 'mainHand',
    quality: 'orange',
    level: 8,
    damage: [18, 26],
    strength: 4, agility: 2,
    power: 16,
    probability: 1,
    sellPrice: 1800,
    durability: 9800, durabilityMax: 9800,
    conditioning: 2450, conditioningMax: 2450,
    width: 1, height: 3,
  },

  // ---------------- Shields (offHand) ----------------
  wooden_shield: {
    itemId: 'wooden_shield',
    name: 'Wooden Shield',
    image: 'wooden-shield',
    type: 'offHand',
    quality: 'common',
    level: 1,
    armor: 10,
    power: 3,
    probability: 30,
    sellPrice: 30,
    durability: 5400, durabilityMax: 5400,
    conditioning: 1350, conditioningMax: 1350,
    width: 2, height: 2,
  },
  reinforced_round_shield: {
    itemId: 'reinforced_round_shield',
    name: 'Round Shield',
    prefix: 'Reinforced',
    image: 'wooden-shield',
    type: 'offHand',
    quality: 'green_plus',
    level: 3,
    armor: 18,
    endurance: 2,
    power: 7,
    probability: 6,
    sellPrice: 240,
    durability: 6800, durabilityMax: 6800,
    conditioning: 1700, conditioningMax: 1700,
    width: 2, height: 2,
  },
  rock_of_aegis: {
    itemId: 'rock_of_aegis',
    name: 'Rock of Aegis',
    image: 'rock-of-aegis',
    type: 'offHand',
    quality: 'purple',
    level: 5,
    armor: 28,
    endurance: 3, strength: 2,
    power: 12,
    probability: 2,
    sellPrice: 600,
    durability: 8200, durabilityMax: 8200,
    conditioning: 2050, conditioningMax: 2050,
    width: 2, height: 2,
  },

  // ---------------- Helmets (head) ----------------
  plate_helmet: {
    itemId: 'plate_helmet',
    name: 'Plate Helmet',
    image: 'plate-helmet',
    type: 'head',
    quality: 'common',
    level: 1,
    armor: 5,
    power: 3,
    probability: 20,
    sellPrice: 30,
    durability: 5200, durabilityMax: 5200,
    conditioning: 1300, conditioningMax: 1300,
    width: 2, height: 2,
  },
  hardened_plate_helmet: {
    itemId: 'hardened_plate_helmet',
    name: 'Plate Helmet',
    prefix: 'Hardened',
    suffix: 'of Vigor',
    image: 'plate-helmet',
    type: 'head',
    quality: 'blue_plus',
    level: 4,
    armor: 14,
    endurance: 3,
    power: 10,
    probability: 4,
    sellPrice: 380,
    durability: 7000, durabilityMax: 7000,
    conditioning: 1750, conditioningMax: 1750,
    width: 2, height: 2,
  },

  // ---------------- Gloves (gloves) ----------------
  leather_gloves: {
    itemId: 'leather_gloves',
    name: 'Leather Gloves',
    image: 'leather-gloves',
    type: 'gloves',
    quality: 'common',
    level: 1,
    armor: 3,
    power: 2,
    probability: 25,
    sellPrice: 20,
    durability: 4800, durabilityMax: 4800,
    conditioning: 1200, conditioningMax: 1200,
    width: 2, height: 2,
  },
  brutal_iron_gauntlets: {
    itemId: 'brutal_iron_gauntlets',
    name: 'Iron Gauntlets',
    prefix: 'Brutal',
    image: 'leather-gloves',
    type: 'gloves',
    quality: 'green',
    level: 2,
    armor: 8,
    strength: 2,
    power: 6,
    probability: 8,
    sellPrice: 130,
    durability: 5800, durabilityMax: 5800,
    conditioning: 1450, conditioningMax: 1450,
    width: 2, height: 2,
  },

  // ---------------- Shoes / Boots (boots) ----------------
  reinforced_boots: {
    itemId: 'reinforced_boots',
    name: 'Reinforced Boots',
    image: 'reinforced-boots',
    type: 'boots',
    quality: 'common',
    level: 1,
    armor: 5,
    power: 3,
    probability: 20,
    sellPrice: 30,
    durability: 5200, durabilityMax: 5200,
    conditioning: 1300, conditioningMax: 1300,
    width: 2, height: 2,
  },
  swift_leather_boots: {
    itemId: 'swift_leather_boots',
    name: 'Leather Boots',
    prefix: 'Swift',
    suffix: 'of the Eagle',
    image: 'reinforced-boots',
    type: 'boots',
    quality: 'green_plus',
    level: 2,
    armor: 7,
    agility: 2,
    power: 6,
    probability: 8,
    sellPrice: 140,
    durability: 5800, durabilityMax: 5800,
    conditioning: 1450, conditioningMax: 1450,
    width: 2, height: 2,
  },

  // ---------------- Rings (ring) ----------------
  ocher_ring: {
    itemId: 'ocher_ring',
    name: 'Ocher Ring',
    image: 'ocher-ring',
    type: 'ring',
    quality: 'green',
    level: 1,
    strength: 2, intelligence: 3,
    power: 5,
    probability: 15,
    sellPrice: 100,
    durability: 4200, durabilityMax: 4200,
    conditioning: 1050, conditioningMax: 1050,
    width: 1, height: 1,
  },
  ring_of_the_wolf: {
    itemId: 'ring_of_the_wolf',
    name: 'Bone Ring',
    suffix: 'of the Wolf',
    image: 'ocher-ring',
    type: 'ring',
    quality: 'blue',
    level: 3,
    agility: 3, dexterity: 2,
    power: 7,
    probability: 5,
    sellPrice: 220,
    durability: 4800, durabilityMax: 4800,
    conditioning: 1200, conditioningMax: 1200,
    width: 1, height: 1,
  },

  // ---------------- Amulets (necklace) ----------------
  choker_of_shielding: {
    itemId: 'choker_of_shielding',
    name: 'Choker of Shielding',
    image: 'choker-of-shielding',
    type: 'necklace',
    quality: 'green',
    level: 1,
    armor: 5, endurance: 5,
    power: 5,
    probability: 10,
    sellPrice: 100,
    durability: 4400, durabilityMax: 4400,
    conditioning: 1100, conditioningMax: 1100,
    width: 1, height: 1,
  },
  heart_of_primal_winter: {
    itemId: 'heart_of_primal_winter',
    name: 'Heart of Primal Winter',
    image: 'heart-of-primal-winter',
    type: 'necklace',
    quality: 'purple_plus',
    level: 4,
    strength: 5, dexterity: 3,
    power: 11,
    probability: 2,
    sellPrice: 480,
    durability: 5600, durabilityMax: 5600,
    conditioning: 1400, conditioningMax: 1400,
    width: 1, height: 1,
  },

  // ---------------- Existing extras (kept for compatibility) ----------------
  planks: {
    itemId: 'planks', name: 'Planks', image: 'planks', type: 'offHand',
    quality: 'common', level: 1, armor: 10, power: 3, probability: 15,
    sellPrice: 30, width: 2, height: 2,
  },
  iron_chest: {
    itemId: 'iron_chest', name: 'Iron Chest', image: 'iron-chest',
    type: 'chest', quality: 'common', level: 1, armor: 10, power: 3,
    probability: 15, sellPrice: 50, width: 2, height: 3,
  },
  vanguard_breastplate: {
    itemId: 'vanguard_breastplate', name: 'Vanguard Breastplate',
    image: 'vanguard-breastplate', type: 'chest', quality: 'blue_plus',
    level: 2, armor: 20, endurance: 2, power: 8, probability: 6,
    sellPrice: 380, width: 2, height: 3,
  },
  chainmail_leggings: {
    itemId: 'chainmail_leggings', name: 'Chainmail Leggings',
    image: 'chainmail-leggings', type: 'legs', quality: 'common',
    level: 1, armor: 5, power: 3, probability: 20, sellPrice: 30,
    width: 2, height: 2,
  },
};
