import type { Metadata } from "next";
import { Cinzel, Inter } from "next/font/google";
import "./globals.css";
import ThemeScript from "@/components/shared/ThemeScript";

const inter = Inter({ subsets: ['latin'] });
const cinzel = Cinzel({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-cinzel',
});

export const metadata: Metadata = {
  title: "Gladiatus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cinzel.variable}>
      <head>
        <ThemeScript />
      </head>
      <body className={`${inter.className} main-scroll main-container`}>
        {children}
      </body>
    </html>
  );
}
