import LandingNavbar from '@/components/shared/LandingNavbar';
import type { Metadata } from 'next';

import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'Gladiatus Clone',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <LandingNavbar />
      <div className='w-full flex justify-center items-center min-h-screen bg-cover' style={{ backgroundImage: 'url("/images/landing-page-image.webp")' }}>
        <Toaster
          toastOptions={{
            className: '',
            style: {
              background: '#eed7a1',
            },
          }}
        />
        {children}
      </div>
    </>
  )
}
