import type { Metadata } from 'next';
import Link from 'next/link';

import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'Gladiatus',
  description: 'Generated by create next app',
}

// Auth layout drops the top navbar; only the Gladiatus logo
// floats in the top-left so the player has a quick way back to
// the landing page.
export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Link
        href='/'
        className='fixed top-2 left-5 cursor-pointer hidden sm:flex z-[998]'
        style={{
          fontFamily: "var(--font-cinzel), 'Cinzel', 'Trajan Pro', 'Times New Roman', serif",
          fontSize: '28px',
          fontWeight: 700,
          letterSpacing: '0.18em',
          color: '#e6b749',
          textShadow:
            '0 1px 0 #3e2714, 0 2px 0 #5c3a21, 0 4px 10px rgba(0,0,0,0.85), 0 0 18px rgba(167, 100, 56, 0.55)',
        }}
      >
        Gladiatus
      </Link>
      <div className='w-full flex justify-center items-center min-h-screen bg-cover' style={{ backgroundImage: 'url("/images/landing-page-image.webp")' }}>
        <Toaster
          toastOptions={{
            className: '',
            style: {
              background: '#eed7a1',
            },
          }}
        />
        {children}
      </div>
    </>
  )
}
